### ISSUE TITLE
Speaker makes cracking sounds?

### ISSUE THREAD

**Issue by ghost** [vladak/truenas_beep#2]
When running spkrtest and selecting one example sounds i hear only cracking sounds from the speaker.

However on reboot the sound is normal like a regular beep.

Any idea maybee? 

I just started with Truenas :)

**Comment by vladak** [comment]
You did not mention what type of speaker this is and also I am not a speaker expert so my only advice would be to try if it works in different OS on the same HW.

Also, reminds me of https://news.ycombinator.com/item?id=27552686 :-)
